name: 打包

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Link File
        shell: pwsh
        run: |
          .\link.ps1 -ci $true
      - name: Read version.txt and save to variable
        shell: pwsh
        run: |
          $mod_version = Get-Content version.txt
          Write-Host "Version: $mod_version"
           echo "MOD_VERSION=$mod_version" | Out-File -Append -Encoding utf8 -FilePath $env:GITHUB_ENV
      - name: build
        run: |
          cd fabric/fabric-1.21
          ./gradlew clean build
          cd ../..
      - uses: actions/upload-artifact@v4
        with:
          name: ChatImage-${{ env.MOD_VERSION }}.jar
          path: ChatImage-jar/${{ env.MOD_VERSION }}/*