name: 打包

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3 # v3.1.0
        - name: build
          shell: pwsh
          run: |
            .\link.ps1