name: 测试NeoForge

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config:
          - { mc-version: '1.20.4', mc-loader: 'neoforge', jdk-version: '17' }
          - { mc-version: '1.20.3', mc-loader: 'neoforge', jdk-version: '17' }
          - { mc-version: '1.20.2', mc-loader: 'neoforge', jdk-version: '17' }

    steps:
      - uses: actions/checkout@v4
      - name: Chose JDK ${{ matrix.config.jdk-version }}
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Read version.txt and save to variable
        shell: pwsh
        run: |
          $mod_version = Get-Content version.txt
          Write-Host "Version: $mod_version"
          echo "MOD_VERSION=$mod_version" | Out-File -Append -Encoding utf8 -FilePath $env:GITHUB_ENV
      - name: build
        run: |
          cd ${{ matrix.config.mc-loader }}/${{ matrix.config.mc-loader }}-${{ matrix.config.mc-version }}
          ./gradlew clean build
          cd ../..
