name: 打包

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Link File
        shell: pwsh
        run: |
          .\link.ps1 -ci $true
      - name: build
        run: |
          cd fabric/fabric-1.21
          ls
          ./gradlew clean build
      - name: read mod version
        run: echo "MY_VARIABLE=Hello, world" >> $GITHUB_ENV