name: 发布到 Github、Curseforge 和 Modrinth

on:
  push:
    branches:
      - fabric-1.18.2
    tags:
      - v1.**
  workflow_dispatch:
    branches:
      - fabric-1.18.2
env:
  MINECRAFT_VERSION: 1.18.2
  JAVA_VERSION: 17
  VERSION: 1.1.5+1.18.2+fabric
  RELEASE_NAME: ChatImage-1.1.5+1.18.2+fabric
#  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
#  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查环境变量
        run: env

      - name: 签出存储库
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: 设置 Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
#
#      - name: 发布（CurseForge/Modrinth/Github）
#        uses: Kir-Antipov/mc-publish@v3.2
#        with:
#          curseforge-id: 818089
#          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"
#
##          modrinth-id: 1q2w3e4r
##          modrinth-token: "${{env.MODRINTH_TOKEN}}"
#
##          github-tag: "v${{env.VERSION}}"
##          github-token: "${{env.GITHUB_TOKEN}}"
#
#          name: "${{env.RELEASE_NAME}}"
#          version: "${{env.VERSION}}"
#          version-type: release
#          changelog-file: CHANGELOG.md
#
#          loaders: fabric
#          game-versions: "${{env.MINECRAFT_VERSION}}"
#          java: "${{env.JAVA_VERSION}}"